jobs:
  include:
   - dist: xenial
     arch: ppc64le
     group: edge
     language: python
     python: '3.7'
     script:
      - ant -version
   - dist: xenial
     arch: s390x
     group: edge
     script:
      - ant -version


