jobs:
  include:
   - dist: focal
     group: edge
     arch: ppc64le
     lang: python
     python: '3.7'
     script:
      - pip install cargo
   - dist: bionic
     group: edge
     arch: ppc64le
     lang: python
     python: '3.7'
     script:
      - pip install cargo
      - ant -version
   - dist: xenial
     arch: ppc64le
     group: edge
     lang: python
     python: '3.7'
     script:
      - pip install cargo
      - ant -version
   - dist: focal
     group: edge
     arch: s390x
     lang: python
     python: '3.7'
     script:
      - pip install cargo
      - ant -version
   - dist: bionic
     group: edge
     arch: s390x
     lang: python
     python: '3.7'
     script:
      - pip install cargo
      - ant -version
   - dist: xenial
     arch: s390x
     group: edge
     lang: python
     python: '3.7'
     script:
      - pip install cargo
      - ant -version


