jobs:
  include:
   - dist: focal
     arch: ppc64le
     script:
      - pip install cargo
      - ant -version
   - dist: bionic
     arch: ppc64le
     script:
      - pip install cargo
      - ant -version
   - dist: xenial
     arch: ppc64le
     script:
      - pip install cargo
      - ant -version
