jobs:
  include:
   - dist: xenial
     jdk: openjdk15
     arch: amd64
     script:
      - java -version
      - echo $JAVA_HOME
      - echo $PATH
   - dist: bionic
     jdk: openjdk15
     arch: amd64
     script:
      - java -version
      - echo $JAVA_HOME
      - echo $PATH
   - dist: focal
     jdk: openjdk15
     arch: amd64
     script:
      - java -version
      - echo $JAVA_HOME
      - echo $PATH

